App_Blog/urls.py
from django.urls import path
from App_Blog import views

app_name='App_Blog'

urlpatterns = [
   path('write/', views.CreateBlog.as_view(), name='create_blog'),
   path('', views.BlogList.as_view(), name='blog_list'),
   path('details/<int:slug> ', views.blog_details, name='blog_details'),
   path('liked/<pk>/',views.liked, name='liked_post'),
   path('unliked/<pk>/',views.unliked, name='unliked_post'),

]



#    path('blog_detail/<str:slug>', views.blog_detail, name="blog_detail"),

App_Login/urls.py
from django.urls import path
from App_Login import views

app_name="App_Login"
urlpatterns = [
    path('signup/',views.sign_up,name='signup'),
    path('login/',views.login_page,name='login'),
    path('logout/',views.logout_user,name='logout'),
    path('profile/',views.profile,name='profile'),
    path('change_profile/',views.user_change,name='change_profile'),
    path('password/',views.pass_change,name='password'),
    path('add-picture/',views.add_pro_pic,name='add_pro_pic'),
    path('change-picture/',views.change_pro_pic,name='change_pro_pic'),
]

Blog_Projects/urls.py
from django.contrib import admin
from django.urls import conf, path, include
from . import views 
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.Index, name='Index')
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    {% comment %} <script src="https://kit.fontawesome.com/bfbacc15c1.js" crossorigin="anonymous"></script> {% endcomment %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>{% block title_block %} Blogs {% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a  class="nav-link" href="{% url 'Index' %}"><img src="/media/bllogo.png" width="50px"></a>
              
            </li>
            {% if user.is_authenticated %}
            <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                    @{{user.username}}
                </a>
                <div class="dropdown-menu">
                    <a  class="dropdown-item" href="{% url 'App_Blog:create_blog' %}">Write Blog</a>
                    <a  class="dropdown-item" href="{% url 'App_Login:profile' %}">Your Profile</a>
                    <hr>
                    <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>
                </div>
            </div>
            {% else %}
            <li class="nav-item">
                <a  class="nav-link" href="{% url 'App_Login:signup' %}">Sign Up</a>
            </li>
       
            <li class="nav-item">
                <a  class="nav-link" href="{% url 'App_Login:login' %}">Login</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    <div class="container" style="padding-top:50px">
        {% block body_block %}

        {% endblock %}
    </div>
</body>  
 